import { AppLanguage, TranslationResource } from './types';

export const TRANSLATIONS: Record<AppLanguage, TranslationResource> = {
  [AppLanguage.ZH]: {
    appTitle: '同声传译 Pro',
    tabConversation: '同声对话',
    tabText: '文本翻译',
    tabCall: '智能通话',
    tabSettings: '设置',
    offlineMode: '离线模式',
    offlineDesc: '下载语言包以在无网络环境下使用。',
    downloadPacks: '离线语言包',
    downloaded: '已下载',
    download: '下载',
    settings: '应用设置',
    selectSource: '源语言',
    selectTarget: '目标语言',
    holdToSpeak: '按住说话',
    listening: '正在聆听...',
    processing: '正在翻译...',
    history: '翻译记录',
    clearHistory: '清除记录',
    sourceLang: '中文',
    targetLang: '外语',
    inputPlaceholder: '请输入要翻译的文本...',
    translateBtn: '翻译',
    enterContact: '输入联系人姓名',
    call: '呼叫',
    calling: '正在呼叫...',
    connected: '通话中',
    endCall: '挂断',
    mute: '静音',
    speaker: '免提',
  },
  [AppLanguage.EN]: {
    appTitle: 'LinguaFlow Pro',
    tabConversation: 'Conversation',
    tabText: 'Text',
    tabCall: 'AI Call',
    tabSettings: 'Settings',
    offlineMode: 'Offline Mode',
    offlineDesc: 'Download language packs for offline use.',
    downloadPacks: 'Offline Packs',
    downloaded: 'Downloaded',
    download: 'Download',
    settings: 'Settings',
    selectSource: 'Source',
    selectTarget: 'Target',
    holdToSpeak: 'Hold to Speak',
    listening: 'Listening...',
    processing: 'Translating...',
    history: 'History',
    clearHistory: 'Clear',
    sourceLang: 'English',
    targetLang: 'Foreign',
    inputPlaceholder: 'Enter text to translate...',
    translateBtn: 'Translate',
    enterContact: 'Enter contact name',
    call: 'Call',
    calling: 'Calling...',
    connected: 'Connected',
    endCall: 'End',
    mute: 'Mute',
    speaker: 'Speaker',
  },
  [AppLanguage.RU]: {
    appTitle: 'Синхронный перевод',
    tabConversation: 'Разговор',
    tabText: 'Текст',
    tabCall: 'Звонок',
    tabSettings: 'Настройки',
    offlineMode: 'Офлайн режим',
    offlineDesc: 'Скачать языковые пакеты для офлайн использования.',
    downloadPacks: 'Языковые пакеты',
    downloaded: 'Скачано',
    download: 'Скачать',
    settings: 'Настройки',
    selectSource: 'Исходный',
    selectTarget: 'Целевой',
    holdToSpeak: 'Удерживайте',
    listening: 'Слушаю...',
    processing: 'Перевод...',
    history: 'История',
    clearHistory: 'Очистить',
    sourceLang: 'Русский',
    targetLang: 'Иностранный',
    inputPlaceholder: 'Введите текст...',
    translateBtn: 'Перевести',
    enterContact: 'Введите имя',
    call: 'Вызов',
    calling: 'Вызов...',
    connected: 'Связь',
    endCall: 'Завершить',
    mute: 'Мут',
    speaker: 'Динамик',
  }
};

export const SUPPORTED_LANGUAGES = [
  { code: AppLanguage.ZH, label: '中文 (Chinese)', flag: '🇨🇳', voiceName: 'zh-CN' },
  { code: AppLanguage.EN, label: 'English', flag: '🇺🇸', voiceName: 'en-US' },
  { code: AppLanguage.RU, label: 'Русский (Russian)', flag: '🇷🇺', voiceName: 'ru-RU' }
];